### ISSUE TITLE
Cutoff option

### ISSUE THREAD

**Issue by edhollinghurst** [hustcc/timeago.js#117]
Has the implementation of a cutoff option ever been considered? This would display the original date if time distance is older than the cutoff.

This is implemented in the jQuery plugin: https://github.com/rmm5t/jquery-timeago

Would you consider a pull request for this feature?

**Comment by hustcc** [comment]
Sounds good. The cutoff time of github maybe one month.

![image](https://cloud.githubusercontent.com/assets/7856674/23779079/183f52bc-0579-11e7-81ae-88505746e757.png)

**But how to show the original date with multi-language?** maybe need to add something in all the locales.

**Comment by edhollinghurst** [comment]
Well if 'Automatic rendering' is used it could simply be specified using the text in the element. E.g.

`<div class="needs_to_be_rendered" datetime="2016-06-30 09:20:00" cutoff="1M">30 Jun 2016</div>`

The text is then only replaced if the timeago value is less than the cutoff.

**Comment by hustcc** [comment]
I think it is nice.

@likerRr What do you think about it?

**Comment by likerRr** [comment]
@hustcc @edhollinghurst Nice idea to have this feature, but we should carefully think about how it should be implemented. 

As far as I understand we need to set a cutoff time not only for DOM nodes, because the library provides ability to format time without any node (`timeago().format()`). Thus `cutofftime` needs to be set during instantiation, e.g.: `timeago(date, locale, cutoff)`.

But if we talk about rendered elements, then at first we should check if the cutoff is set in the node's attribute, and if no - check if it was set during instantiation. This way each rendered element can have it's own cutoff time or common one which was set during instantiation.

The second thing to think about is the form of cutofftime: timestamp, hours/minutes/seconds since the `nowDate`, string, `Date` instance or a short format like 1H(our), 10M(inutes).

**Comment by hustcc** [comment]
Really complicated.

**Comment by likerRr** [comment]
Sorry :smile:

**Comment by hustcc** [comment]
@edhollinghurst So the feature of cutoff will not be supported because of great changes.

**Comment by edhollinghurst** [comment]
OK thanks for considering it.
