### ISSUE TITLE
Support 'today', 'tomorrow', 'yesterday' when time is not specified

### ISSUE THREAD

**Issue by aghassemi** [hustcc/timeago.js#137]
Would be nice to have fuzzier formatting by omitting time. Use-cases such as "In theaters <in 2 days, tomorrow, today>" can benefit from this.

**Comment by hustcc** [comment]
Means when date such as `2017-07-14` is given, then shows `tomorrow `?

How many fuzzier formatting strings?

**Comment by aghassemi** [comment]
Yes, Exactly

**Comment by likerRr** [comment]
I think you can add a custom language and implement this logic yourself, e.g.:

```javascript
// number here is the difference
// index represents a period, for day it will be 6 and 7
// so you can easily calculate when to display `tomorrow`
module.exports = function(number, index) {
  if (index === 6 /* because a single day */) {
    return ['yesterday', 'tomorrow'];
  }

  if (index >= 0 && index < 6) {
    return ['today', 'today'];
  }

  return [
    [/*'just now', 'right now'*/],
    [/*'%s seconds ago', 'in %s seconds'*/],
    [/*'1 minute ago', 'in 1 minute'*/],
    [/*'%s minutes ago', 'in %s minutes'*/],
    [/*'1 hour ago', 'in 1 hour'*/],
    [/*'%s hours ago', 'in %s hours'*/],
    [/*'1 day ago', 'in 1 day'*/],
    ['%s days ago', 'in %s days'],
    ['1 week ago', 'in 1 week'],
    ['%s weeks ago', 'in %s weeks'],
    ['1 month ago', 'in 1 month'],
    ['%s months ago', 'in %s months'],
    ['1 year ago', 'in 1 year'],
    ['%s years ago', 'in %s years']
  ][index];
}
```

**Comment by aghassemi** [comment]
Thanks @likerRr! We will implement it as suggested on our side.

Closing the issue.

**Comment by sublimeye** [comment]
I have an issue with this approach.

Let's say now is "November 1 19:00"
If I set the date to "November 2 13:00" it still returns "today" even though it's definitely not today. Is there a workaround to support correct recognition of yesterday/today/tomorrow?

**Comment by likerRr** [comment]
@sublimeye can you solve your issue by just changing the wording from "today" to e.g. "in a day"?

**Comment by sublimeye** [comment]
@likerRr Well, I could solve it by changing the wording to "tomorrow" but the problem is that library is "numbers" oriented and I'm not sure if there's a way to change the behavior.

Here's an example:
Now is "23:00 January 1st"
You check *timeago* against "02:00 January 2nd".
The library will return *in 3 hours* whereas I would want it to say "tomorrow".

Even if you create your own "customization" library you can see amount of hours / days and can change the wording, but you can't tell if it's actually "tomorrow" or today. All you know it's in 3 hours ...
