### ISSUE TITLE
v4.0.0 is working in progress

### ISSUE THREAD

**Issue by hustcc** [hustcc/timeago.js#156]
Working code is on branch `master`.

 - rewrite with es6.
 - coverage test cases to 100% with jest.
 - refactoring code structure.
 - bundle with rollup & babel.

## What to be done?

- [x] test coverage, src & locales
- [x] code of locales translated to ES6
- [x] new API design
- [x] locale file format

### new API

```js
import { format, render, cancel, register } from 'timeago.js';

// format date to string
const str = format(date, locale);

// real time render
render(dom, locale);

cancel(dom); // cancel the dom

cancel(); // cancel all

// new locale
register('new_locale', localeFunc);
```

> Welcome to pr and discuss.

**Comment by likerRr** [comment]
Hey, nice news about v4
Why did you chose rollup for bundling?

**Comment by hustcc** [comment]
For tiny library, rollup bundle size is smaller then webpack. Webpack's module code can reach to 1 kb.

Is there any other better choice?

**Comment by likerRr** [comment]
It's difficult to say in advance. I haven't tried rollup, but I used to work with webpack for a long time. I think we can compare the resulting bundle size when v4 is ready and then chose the better one

**Comment by hustcc** [comment]
@likerRr v4 is always ready. You can do your test. Thank you.

**Comment by IceCreamYou** [comment]
I see that several months ago there was a beta release of v4 on npm, however I don't see the corresponding tag or commits on GitHub. As a result I am unable to determine if I should upgrade because there is no list of changes, and it sounds like some of the changes could be backwards-incompatible.

Would it be possible to publish the changes on GitHub or at least provide a list of the differences between 3.0.2 and 4.0.0-beta.1?

**Comment by hustcc** [comment]
@IceCreamYou Sorry for confusing, 3.0.2 recommended for you.

**Comment by Textras** [comment]
@hustcc is 4.0.0-beta.1 production-ready? I see this discussion was from Dec 2018 and no removal of beta flag. Thanks.

**Comment by hustcc** [comment]
The week will be release v4.0.0.
