### ISSUE TITLE
[discuss] v2.0.x version 

### ISSUE THREAD

**Issue by hustcc** [hustcc/timeago.js#67]
:walking:  The v1.x.x received so many feedbacks and suggestions, so v2.0.x will do it.

v2.0.x will not compatible with v1.0.x, details below:
- [x] Read date from `datetime` attribute for `<time datetime='xxxxx'>`.
- [x] API `register` will be a static method, replace of an instance method.
- [x] Will use coding style of `new timeago()`.

What else, welcome to additional.
ref #12 #23 #47 #59 #61

**Comment by hustcc** [comment]
see branch [v2.0.x](https://github.com/hustcc/timeago.js/tree/v2.0.x).

**Comment by hustcc** [comment]
@breeswish @cocody @likerRr @shaneog @simevidas @RyanZim

Just have a look at v2.0.x futures on master branch.

**Comment by simevidas** [comment]
Usage with `<time datetime>` seems to work 👍, after running:

```
new timeago().render(document.querySelectorAll('time'));
```

**[Live demo](https://jsbin.com/nonusu/edit?html,output).**

![capture](https://cloud.githubusercontent.com/assets/716405/18612927/b80ae820-7d6a-11e6-996b-7dbc69d03d08.PNG)

**Comment by likerRr** [comment]
Hi, @hustcc ! Great work and I have few words to add. Give me a time to summarize and I will post my minds with PRs, thx.

**Comment by hustcc** [comment]
@likerRr ok, waiting~

**Comment by likerRr** [comment]
@hustcc , here are my minds and some improvements suggestions.

### `Will use coding style of new timeago()`

Using word `new` is not just a `style`. It has its [own meaning](https://css-tricks.com/understanding-javascript-constructors/) at the language layer. Sorry, but function constructor implementation in v2 is wrong and it pollutes global object with its own methods when is called like `timeago(null, '2016-06-23')` (then open devtools and execute `console.log(window.format);console.log(window.render);console.log(window.cancel);` and you will see that all these methods are in the global scope, 😵).

### Naming convention inconsistency

Compare:
- [`indexMapEn`](https://github.com/hustcc/timeago.js/blob/master/src/timeago.js#L15) and [`attr_datetime`](https://github.com/hustcc/timeago.js/blob/master/src/timeago.js#L38)
- [`toDate`](https://github.com/hustcc/timeago.js/blob/master/src/timeago.js#L96) and [`left_sec`](https://github.com/hustcc/timeago.js/blob/master/src/timeago.js#L116)

I strongly suggest to use `camelCase` as internal JavaScript functions/variables do ([`toString`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Function/toString)/[`byteLength`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/ArrayBuffer/byteLength) and [uppercase characters separated by underscores for constants](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Number/MIN_SAFE_INTEGER))

### `Set defaultLocale as the 1st parameter of timeago().`

It's very interesting change, but as you can see it becomes very ugly [each](https://github.com/hustcc/timeago.js/blob/master/tests/test.js#L25) [time](https://github.com/hustcc/timeago.js/blob/master/tests/test.js#L26) [skip](https://github.com/hustcc/timeago.js/blob/master/tests/test.js#L27) [first](https://github.com/hustcc/timeago.js/blob/master/tests/test.js#L28) parameter in order to specify date and time. Since library is about the time, I think that the first parameter should be a time. And for me it's not clear why there are more cases to specify first parameter as a locale then a time as requested here #61?
We have many ways to specify a locale and it doesn't seem to be unfriendly:
1. timeago().setLocale('en');
2. timeago().format('', 'en');
3. timeago('', 'en');

I made a PR #68 with corresponding changes. I made these changes consistently so you can learn every commit step by step. I not pretend to include it all, but at least try to understand what I've meant.

P.S. Unfortunately the size of library increased and in PR it's about 2.18KB, but again performance or size - you choose 😜

**Comment by breezewish** [comment]
Cheers.

@likerRr A better solution might be using `options`?
`options.locale`
`options.baseTime`
etc.

**Comment by breezewish** [comment]
@likerRr

I think (guess) the position of this library is to present relative time to users in a lite way. That's why it includes the most interesting and **unique** feature: automatic update relative time text. In this scenario, users are likely to use current time as the base time and changing the base time is minimal. On the other hand, since the contribution of i18n is very active, changing locale might be not a rare case.

**Comment by hustcc** [comment]
@likerRr I run in `timeago.js`, the API is not in gloabal scope.

![image](https://cloud.githubusercontent.com/assets/7856674/18620726/a4fcd384-7e4a-11e6-8245-744fb0a478bb.png)
![image](https://cloud.githubusercontent.com/assets/7856674/18620727/b68bf83c-7e4a-11e6-88bc-80821c508cb4.png)

@breeswish the order of paramter has no effect on locales. About the paramters order, you all hava principles, but considering v1.x.x, I think keep the order same with v1.x.x is OK.

**Comment by likerRr** [comment]
@hustcc Hi! Please, read carefully: `when is called like timeago(null, '2016-06-23')`. [Here](http://jsbin.com/qeqenuwika/edit?js,console) is the fiddle if we can't understand each other. I just made accent on this because when function constructor is implemented correctly then it won't be such issues. And there is such [usage](https://github.com/hustcc/timeago.js/blob/master/tests/test.js#L30) in tests.

@breeswish Hi, thank you! Sorry, but I think there is nothing common in how often users contribute in i18n and how they use the library. In my opinion you set the localization once, when you init the library or when use `setLocale` method. And you said it:

> I think (guess) the position of this library is to present relative time to users in a lite way

Time first, locale second

**Comment by breezewish** [comment]
@likerRr I don't think everyone will come to an agreement on this issue since their requirements and the reasons of using this library are different. As I said before, `options` can be considered in the next version. It is a ultimate, good, comfort-for-all solution.

**Comment by likerRr** [comment]
@breeswish I can't say that `options` is better, it complicates the usage. Anyway, `options` will be placed as the second parameter, so how it will differ from putting `locale` as the second parameter?

**Comment by breezewish** [comment]
@likerRr What I'm saying is:

``` js
options: {
  baseTime: ...,
  locale: ...,
}
```

**Comment by hustcc** [comment]
The parameters's order is `timeago(now_date, locale_name)`, same with v1.0.x. Pass this point. @likerRr  @breeswish

**Comment by likerRr** [comment]
@hustcc ok, so I have nothing new to add

**Comment by shaneog** [comment]
@hustcc Looking very nice!

I'm not seeing how this will resolve #23 though? I can see `locales.js` but nothing extra in the `/dist` folder.

**Comment by shaneog** [comment]
👍 from me!

**Comment by hustcc** [comment]
Then, close this issue ?

**Comment by likerRr** [comment]
I think yes, we've done here
