### ISSUE TITLE
Webpack vs Gulp

### ISSUE THREAD

**Issue by ClemMakesApps** [hustcc/timeago.js#87]
I had a question as to why we are using gulp and webpack. Why not just use one or the other?

**Comment by likerRr** [comment]
@ClemMakesApps I think it's because of size. I made test build of `timeago` with `webpack2` + `uglify` plugin and the final size was more then just with `uglifyjs` running by `gulp`. The main problem is that `webpack` generates extra code for require functionality and wraps each module in kind of IIFE. 

Since `timeago` very small it doesn't have a lot of modules (actually it's one module) so using `webpack` here will be overhead.

P.S. `gulp` and `webpack` responsible for different kind of tasks, they are not interchangeable (but sometimes they do)
